Venkatesh Godi-BMB2058

In [ ]:
import numpy as np
a=np.array([0,1,2,3])
print(a)

[0 1 2 3]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
print(a.dtype)

int64


In [ ]:
print(a.shape)

(4,)


In [ ]:
print(a.size)

4


In [ ]:
print(a.ndim)

1


In [ ]:
print(a.nbytes)

32


In [ ]:
import numpy as np
a=np.array([[0,1,2,3],[10,11,12,13]])
print(a)

[[ 0  1  2  3]
 [10 11 12 13]]


In [ ]:
print(type(a))
print(a.dtype)
print(a.shape)

<class 'numpy.ndarray'>
int64
(2, 4)


In [ ]:
print(a.size)
print(a.ndim)
print(a.nbytes)

8
2
64


In [ ]:
import numpy as np
print(np.__version__)

2.0.2


**Zero dimensional array**

In [ ]:
import numpy as np
arr=np.array(2)
print(arr)
print("Size of array-",arr.size)
print("Shape of array -",arr.shape)
print(type(arr))
print("Dimension of array-",arr.ndim)

2
Size of array- 1
Shape of array - ()
<class 'numpy.ndarray'>
Dimension of array- 0


**1Dimensional array**

In [ ]:
import numpy as np
arr=np.array([2])
print(arr)
print("Size of array-",arr.size)
print("Shape of array -",arr.shape)
print(type(arr))
print("Dimension of array-",arr.ndim)

[2]
Size of array- 1
Shape of array - (1,)
<class 'numpy.ndarray'>
Dimension of array- 1


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print("Size of array-",arr.size)
print("Shape of array -",arr.shape)
print(type(arr))
print("Dimension of array-",arr.ndim)

[1 2 3 4 5]
Size of array- 5
Shape of array - (5,)
<class 'numpy.ndarray'>
Dimension of array- 1


**2 Dimensional array**

In [ ]:
import numpy as np
arr=np.array([[1,2,8],[3,4,9],[5,6,7]])
print(arr)
print("Size of array-",arr.size)
print("Shape of array -",arr.shape)
print(type(arr))
print("Dimension of array-",arr.ndim)

[[1 2 8]
 [3 4 9]
 [5 6 7]]
Size of array- 9
Shape of array - (3, 3)
<class 'numpy.ndarray'>
Dimension of array- 2


**If one element is float then remaining elements will also converted into float.**

In [ ]:
import numpy as np
arr=np.array([[2.0,1],[1,2]])
print(arr)

[[2. 1.]
 [1. 2.]]


**Create an array with 5 dimensions and verify that it has 5 dimensions.**

In [ ]:
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print("Dimension of array",arr.ndim)

[[[[[1 2 3 4]]]]]
Dimension of array 5


**Array indexing.**

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
sum=arr[2]+arr[3]
print(sum)

7


In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0,1])
print(arr[1,4])

2
10


In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr)
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
6


**Basic arithmetic operations.**

In [ ]:
import numpy as np
arr=np.array([1,3,5,7,9])
sum=arr[0]+arr[2]
dif=arr[2]-arr[3]
mul=arr[1]*arr[2]
div=arr[4]/arr[1]
print(sum)
print(dif)
print(mul)
print(div)


6
-2
15
3.0


**Slicing 1D Array.**

In [ ]:
import numpy as np
            #-8 -7 -6 -5 -4  -3  -2  -1
            # 0  1  2  3  4   5   6   7
arr=np.array([2, 4, 6, 8, 10, 12, 14, 16])
print(arr[3:6])
print(arr[:5])
print(arr[2:])
print(arr[-5:-1])
print(arr[:-1])

[ 8 10 12]
[ 2  4  6  8 10]
[ 6  8 10 12 14 16]
[ 8 10 12 14]
[ 2  4  6  8 10 12 14]


**Slicing 2D array**

In [ ]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr[0:2,2])
print(arr[0:2,1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


**Copy**

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


**Reshaping**

In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
a.shape=(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


**Create a 1D array with 12 elements and convert that into 2D array as 4*3 elements.**

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=a.reshape(3,4,2)
print(newarr)

ValueError: cannot reshape array of size 12 into shape (3,4,2)

Create 1D array with 12 elements.Convert it into 3D the outermost dimension will have 2 arrays, that contains 3 arrays each with 2 elements.

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=a.reshape(2,3,2)
print(newarr)

**Range**

In [ ]:
import numpy as np
np .arange(1,5)

In [ ]:
import numpy as np
np .arange(1,14,4)

**Elements arithmetic operatins. **

In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(arr1)
print(arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1@arr2)

In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6,7],[8,9,10]])
print(arr1)
print(arr2)
print(arr1+arr2)

In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6,7],[8,9,10]])
print(arr1)
print(arr2)
print(arr1-arr2)

In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6,7],[8,9,10]])
print(arr1)
print(arr2)
print(arr1*arr2)

In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6,7],[8,9,10]])
print(arr1)
print(arr2)
print(arr1/arr2)

In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6,7],[8,9,10]])
print(arr1)
print(arr2)
print(arr1@arr2)

**Concatenating of two arrays.**
**If axis=0 then it concatenates along rows.**

In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
concatenated_arr=np.concatenate((arr1,arr2),axis=0)
print(concatenated_arr)

**If axis=1 then it concatenates along columns.**

In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
concatenated_arr=np.concatenate((arr1,arr2),axis=1)
print(concatenated_arr)

**Transpose-Interchange the rows and columns.
Shape of the matrix will also interchanged by number of rows and number of columns.**

In [ ]:
import numpy as np
arr1=np.array([[1,2,3,4],[6,7,8,9]])
transpose_arr=arr1.transpose()
print(arr1)
print(transpose_arr)

**Flatten-Converts multi dimension into single dimension.**

In [ ]:
import numpy as np
arr1=np.array([[1,2,3,4],[6,7,8,9]])
flattened_arr=arr1.flatten()
print(arr1)
print(flattened_arr)

In [ ]:
import numpy as np
a=np.array([1+1j,1,4.5,3,2,2j])
print("Original array-")
print(a)
print("Checking for complex numbers-")
print(np.iscomplex(a))
print("Checking for real numbers-")
print(np.isreal(a))
print("Checking for scalar type-")
print(np.isscalar(3.1))
print(np.isscalar([3.1]))

In [ ]:
import numpy as np
arr=np.zeros(5)
print(arr)

In [ ]:
import numpy as np
arr=np.zeros((2,3))
print(arr)

In [ ]:
import numpy as np
arr=np.ones((2,4))
print(arr)

In [ ]:
import numpy as np
arr=np.empty((2,3))
print(arr)

In [ ]:
import numpy as np
arr=np.empty((2,3))
print(arr)

In [ ]:
import numpy as np
crop_yields=np.array([[12.5,13.2,14.1,13.8,15.2],
              [10.3,11.5,10.8,12.1,11.9],
              [15.1,14.8,16.2,15.5,16.8],
              [11.2,10.9,12.3,11.7,12.8],
              ])
print("Crop yield array(tons):")
print(crop_yields)
print("\nShape",crop_yields.shape)
print(f'Data type:{crop_yields.dtype}')
print("Total elements:",crop_yields.size)
print("Dimension:",crop_yields.ndim)

In [ ]:
total_yield=np.sum(crop_yields)
print("Total yield:",total_yield)

In [ ]:
median=np.median(crop_yields)
print("Median of crop yield:",median)

In [ ]:
sd=np.std(crop_yields)
print("Standard deviation:",sd)

**Axis=1--along the rows,
it gives the average among rows.**

In [ ]:
avg_yield_per_farm=np.mean(crop_yields,axis=1)
print("Mean yield per farm:",avg_yield_per_farm)

In [ ]:
avg_yield_per_farm=np.mean(crop_yields)
print("Mean yield per farm:",avg_yield_per_farm)

**Axis=0--along the columns,
it gives the average among columns.**

In [ ]:
avg_yield_per_season=np.mean(crop_yields,axis=0)
print("Mean yield per season:",avg_yield_per_season)

In [ ]:
max_yield=np.max(crop_yields)
print("Maximum yield:",max_yield,"tons")

In [ ]:
min_yield=np.min(crop_yields)
print("Minimum yield:",min_yield,"tons")

In [ ]:
max_yield=np.max(crop_yields,axis=1)
print("Maximum yield:",max_yield)

In [ ]:
max_yield=np.max(crop_yields,axis=0)
print("Maximum yield:",max_yield)

In [ ]:
min_yield=np.min(crop_yields,axis=1)
print("Minimum yield:",min_yield)

In [ ]:
min_yield=np.min(crop_yields,axis=0)
print("Minimum yield:",min_yield)

In [ ]:
best_farm=np.argmax(avg_yield_per_farm)
print("Best farm:",best_farm+1)
print('Their average yield:',round(avg_yield_per_farm[best_farm],2),"tons")

In [ ]:
worst_farm=np.argmin(avg_yield_per_farm)
print("Worst farm:",worst_farm+1)
print("Their average yield:",round(avg_yield_per_farm[worst_farm],1),"tons/ha")

In [ ]:
exceptional=crop_yields>16
print("\nExceptional yields(>16)")
print(crop_yields[exceptional])

In [ ]:
exceptional=crop_yields>15
print("\nExceptional yields(>15)")
print(crop_yields[exceptional])

In [ ]:
categories=np.where(crop_yields>16,"High",np.where(c))